-- ============================================================
-- EWallet Development Seed Data
-- ============================================================
-- IMPORTANT: Before running this script, replace both
-- PLACEHOLDER_HASH_REPLACE_ON_FIRST_RUN values with real
-- BCrypt hashes generated by:
--   BCrypt.Net.BCrypt.HashPassword("Admin@1234!", workFactor: 12)
--   BCrypt.Net.BCrypt.HashPassword("Test@1234!",  workFactor: 12)
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------------------------
-- Seed admin user (password: Admin@1234!)
-- BCrypt hash of "Admin@1234!" with work factor 12
-- ------------------------------------------------------------
INSERT INTO users (
    id,
    email,
    phone_number,
    full_name,
    password_hash,
    kyc_level,
    is_two_factor_enabled,
    is_active,
    created_at
)
VALUES (
    'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    'admin@ewallet.dev',
    '+15551234567',
    'System Admin',
    '$2a$12$PLACEHOLDER_HASH_REPLACE_ON_FIRST_RUN',
    3,      -- KYC Tier 3 (fully verified)
    false,
    true,
    NOW()
)
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------
-- Seed test user 1 (password: Test@1234!)
-- BCrypt hash of "Test@1234!" with work factor 12
-- ------------------------------------------------------------
INSERT INTO users (
    id,
    email,
    phone_number,
    full_name,
    password_hash,
    kyc_level,
    is_two_factor_enabled,
    is_active,
    created_at
)
VALUES (
    'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    'alice@example.com',
    '+15559876543',
    'Alice Smith',
    '$2a$12$PLACEHOLDER_HASH_REPLACE_ON_FIRST_RUN',
    2,      -- KYC Tier 2 (partially verified)
    false,
    true,
    NOW()
)
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------
-- Seed wallets for the above users
-- ------------------------------------------------------------
INSERT INTO wallets (
    id,
    user_id,
    balance_amount,
    balance_currency,
    is_locked,
    created_at
)
VALUES
    (
        uuid_generate_v4(),
        'a1b2c3d4-e5f6-7890-abcd-ef1234567890',  -- admin
        10000.00,
        'USD',
        false,
        NOW()
    ),
    (
        uuid_generate_v4(),
        'b2c3d4e5-f6a7-8901-bcde-f12345678901',  -- alice
        5000.00,
        'USD',
        false,
        NOW()
    )
ON CONFLICT DO NOTHING;
